apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
stringData:
  # Replace the values or create this secret with kubectl create secret generic --from-env-file=apiserver/.config.env -n dev
  DB_USER: "postgres"
  DB_PASS: "REPLACE_WITH_DB_PASSWORD"
  JWT_VERIFY_SECRET: "REPLACE_JWT_VERIFY_SECRET"
  JWT_SESSION_SECRET: "REPLACE_JWT_SESSION_SECRET"
  JWT_REFRESH_SECRET: "REPLACE_JWT_REFRESH_SECRET"
  SENDGRID_API_KEY: ""